-- Vérifier les données dans la table VEHICULE
SELECT ID_VEHI, IMMAT, MARQUE, MODELE, TYPE, ETAT, 
       SUBSTR(SERVICE, 1, 30) AS SERVICE_PREVIEW, 
       TO_CHAR(DATE_MAINT, 'DD/MM/YYYY') AS DATE_MAINT
FROM VEHICULE
ORDER BY ID_VEHI;

-- Vérifier le nombre de véhicules
SELECT COUNT(*) AS NB_VEHICULES FROM VEHICULE;

EXIT;
