-- ============================================================
-- SCRIPT DE CRÉATION DES TABLES POUR SMART CITY - Oracle 11g
-- ============================================================

-- Supprimer les tables si elles existent (pour recréation)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE GEST_HISTORIQUE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE GEST_ALERTES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Créer la séquence pour les alertes
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALERTES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SEQ_ALERTES START WITH 1 INCREMENT BY 1;

-- Créer la séquence pour l'historique
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HISTORIQUE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SEQ_HISTORIQUE START WITH 1 INCREMENT BY 1;

-- Table des alertes (compatible Oracle 11g)
CREATE TABLE GEST_ALERTES (
    ID NUMBER PRIMARY KEY,
    ID_MAISON NUMBER NOT NULL,
    ZONE VARCHAR2(255),
    NIVEAU NUMBER CHECK (NIVEAU BETWEEN 1 AND 5),
    STATUT VARCHAR2(50),
    DATE_ALERTE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ALERTE_MAISON FOREIGN KEY (ID_MAISON) REFERENCES GEST_MAISON(ID) ON DELETE CASCADE
);

-- Table historique (compatible Oracle 11g)
CREATE TABLE GEST_HISTORIQUE (
    ID NUMBER PRIMARY KEY,
    ID_RESIDENT VARCHAR2(20),
    ACTION VARCHAR2(100) NOT NULL,
    DETAILS VARCHAR2(500),
    DATE_ACTION DATE DEFAULT SYSDATE,
    UTILISATEUR VARCHAR2(50)
);

-- Index pour améliorer les performances
CREATE INDEX IDX_RESIDENT_ADRESSE ON GEST_RESIDENT(ADRESSE);
CREATE INDEX IDX_ALERTE_MAISON ON GEST_ALERTES(ID_MAISON);
CREATE INDEX IDX_ALERTE_STATUT ON GEST_ALERTES(STATUT);
CREATE INDEX IDX_HISTORIQUE_DATE ON GEST_HISTORIQUE(DATE_ACTION);
CREATE INDEX IDX_HISTORIQUE_RESIDENT ON GEST_HISTORIQUE(ID_RESIDENT);

-- Trigger pour auto-incrémenter l'ID des alertes
CREATE OR REPLACE TRIGGER TRG_ALERTES_ID
BEFORE INSERT ON GEST_ALERTES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_ALERTES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger pour auto-incrémenter l'ID de l'historique
CREATE OR REPLACE TRIGGER TRG_HISTORIQUE_ID
BEFORE INSERT ON GEST_HISTORIQUE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_HISTORIQUE.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger pour l'historique lors de l'ajout d'un résident
CREATE OR REPLACE TRIGGER TRG_RESIDENT_INSERT
AFTER INSERT ON GEST_RESIDENT
FOR EACH ROW
BEGIN
    INSERT INTO GEST_HISTORIQUE (ID_RESIDENT, ACTION, DETAILS, UTILISATEUR)
    VALUES (:NEW.ID, 'AJOUT', 'Nouveau résident: ' || :NEW.NOM || ' ' || :NEW.PRENOM, USER);
END;
/

-- Trigger pour l'historique lors de la modification d'un résident
CREATE OR REPLACE TRIGGER TRG_RESIDENT_UPDATE
AFTER UPDATE ON GEST_RESIDENT
FOR EACH ROW
BEGIN
    INSERT INTO GEST_HISTORIQUE (ID_RESIDENT, ACTION, DETAILS, UTILISATEUR)
    VALUES (:NEW.ID, 'MODIFICATION', 'Résident modifié: ' || :NEW.NOM || ' ' || :NEW.PRENOM, USER);
END;
/

-- Trigger pour l'historique lors de la suppression d'un résident
CREATE OR REPLACE TRIGGER TRG_RESIDENT_DELETE
BEFORE DELETE ON GEST_RESIDENT
FOR EACH ROW
BEGIN
    INSERT INTO GEST_HISTORIQUE (ID_RESIDENT, ACTION, DETAILS, UTILISATEUR)
    VALUES (:OLD.ID, 'SUPPRESSION', 'Résident supprimé: ' || :OLD.NOM || ' ' || :OLD.PRENOM, USER);
END;
/

-- Trigger pour créer automatiquement une alerte si sécurité < 3
CREATE OR REPLACE TRIGGER TRG_MAISON_SECURITE
AFTER INSERT OR UPDATE OF SECURITE ON GEST_MAISON
FOR EACH ROW
WHEN (NEW.SECURITE < 3)
DECLARE
    v_count NUMBER;
BEGIN
    -- Vérifier si une alerte n'existe pas déjà pour cette maison
    SELECT COUNT(*) INTO v_count
    FROM GEST_ALERTES
    WHERE ID_MAISON = :NEW.ID AND STATUT != 'Traitée';
    
    IF v_count = 0 THEN
        INSERT INTO GEST_ALERTES (ID_MAISON, ZONE, NIVEAU, STATUT)
        VALUES (:NEW.ID, :NEW.ADRESSE, :NEW.SECURITE, 'En attente');
    END IF;
END;
/

COMMIT;

-- Afficher le résultat
SELECT 'Tables GEST_ALERTES et GEST_HISTORIQUE créées avec succès!' AS MESSAGE FROM DUAL;
