-- =====================================================
-- CREATION DES TABLES MAINTENANCE ET RECOMMANDATION_PLANTE
-- Pour le module de gestion des jardins
-- =====================================================

-- Table MAINTENANCE
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('Table MAINTENANCE supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
      DBMS_OUTPUT.PUT_LINE('Table MAINTENANCE n''existe pas encore');
END;
/

CREATE TABLE MAINTENANCE (
    ID_MAINTENANCE NUMBER PRIMARY KEY,
    ID_JARDIN NUMBER NOT NULL,
    TYPE_MAINTENANCE VARCHAR2(100 BYTE),
    DESCRIPTION VARCHAR2(500 BYTE),
    DATE_EFFECTUEE DATE,
    DATE_RECOMMANDEE DATE,
    STATUT VARCHAR2(50 BYTE),
    FREQUENCE VARCHAR2(50 BYTE),
    CONSTRAINT FK_MAINTENANCE_JARDIN FOREIGN KEY (ID_JARDIN) REFERENCES GEST_JARDIN(ID_JARDIN) ON DELETE CASCADE
);

-- Table RECOMMANDATION_PLANTE
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RECOMMANDATION_PLANTE CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('Table RECOMMANDATION_PLANTE supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
      DBMS_OUTPUT.PUT_LINE('Table RECOMMANDATION_PLANTE n''existe pas encore');
END;
/

CREATE TABLE RECOMMANDATION_PLANTE (
    ID_PLANTE NUMBER PRIMARY KEY,
    TYPE_SOL VARCHAR2(100 BYTE) NOT NULL,
    RECOMMANDATION VARCHAR2(1000 BYTE),
    NOM_PLANTE VARCHAR2(200 BYTE),
    COMPATIBILITE VARCHAR2(50 BYTE) DEFAULT 'Moyenne',
    SAISON VARCHAR2(50 BYTE),
    CONSTRAINT CHK_COMPATIBILITE CHECK (COMPATIBILITE IN ('Excellente', 'Bonne', 'Moyenne', 'Faible'))
);

COMMIT;

-- Insérer des données de test pour MAINTENANCE
INSERT INTO MAINTENANCE (ID_MAINTENANCE, ID_JARDIN, TYPE_MAINTENANCE, DESCRIPTION, DATE_EFFECTUEE, DATE_RECOMMANDEE, STATUT, FREQUENCE)
VALUES (1, 1, 'Arrosage', 'Arrosage régulier du jardin central', TO_DATE('2025-12-01', 'YYYY-MM-DD'), TO_DATE('2025-12-15', 'YYYY-MM-DD'), 'Effectué', 'Hebdomadaire');

INSERT INTO MAINTENANCE (ID_MAINTENANCE, ID_JARDIN, TYPE_MAINTENANCE, DESCRIPTION, DATE_EFFECTUEE, DATE_RECOMMANDEE, STATUT, FREQUENCE)
VALUES (2, 1, 'Taille', 'Taille des arbustes et haies', NULL, TO_DATE('2025-12-20', 'YYYY-MM-DD'), 'En attente', 'Mensuelle');

INSERT INTO MAINTENANCE (ID_MAINTENANCE, ID_JARDIN, TYPE_MAINTENANCE, DESCRIPTION, DATE_EFFECTUEE, DATE_RECOMMANDEE, STATUT, FREQUENCE)
VALUES (3, 2, 'Désherbage', 'Élimination des mauvaises herbes', TO_DATE('2025-11-25', 'YYYY-MM-DD'), TO_DATE('2025-12-10', 'YYYY-MM-DD'), 'Effectué', 'Bimensuelle');

INSERT INTO MAINTENANCE (ID_MAINTENANCE, ID_JARDIN, TYPE_MAINTENANCE, DESCRIPTION, DATE_EFFECTUEE, DATE_RECOMMANDEE, STATUT, FREQUENCE)
VALUES (4, 3, 'Fertilisation', 'Application d''engrais organique', NULL, TO_DATE('2025-12-25', 'YYYY-MM-DD'), 'Planifié', 'Trimestrielle');

INSERT INTO MAINTENANCE (ID_MAINTENANCE, ID_JARDIN, TYPE_MAINTENANCE, DESCRIPTION, DATE_EFFECTUEE, DATE_RECOMMANDEE, STATUT, FREQUENCE)
VALUES (5, 4, 'Inspection', 'Vérification de l''état général du jardin', TO_DATE('2025-12-05', 'YYYY-MM-DD'), TO_DATE('2026-01-05', 'YYYY-MM-DD'), 'Effectué', 'Mensuelle');

-- Insérer des données de test pour RECOMMANDATION_PLANTE
INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (1, 'Argileux', 'Sol riche et compact, excellent pour les rosiers. Arrosage modéré recommandé.', 'Rosier', 'Excellente', 'Printemps');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (2, 'Argileux', 'Bon drainage nécessaire. Plante résistante aux sols lourds.', 'Lavande', 'Bonne', 'Été');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (3, 'Sableux', 'Sol drainant parfait pour les cactus. Arrosage minimal.', 'Cactus', 'Excellente', 'Été');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (4, 'Sableux', 'Bon drainage, supporte bien la sécheresse.', 'Romarin', 'Bonne', 'Printemps');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (5, 'Limoneux', 'Sol fertile idéal pour les légumes. Très productif.', 'Tomate', 'Excellente', 'Été');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (6, 'Limoneux', 'Sol équilibré, parfait pour la croissance.', 'Carotte', 'Excellente', 'Automne');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (7, 'Calcaire', 'Sol alcalin adapté. Préfère les conditions sèches.', 'Thym', 'Bonne', 'Printemps');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (8, 'Calcaire', 'Supporte bien le calcaire. Floraison abondante.', 'Clématite', 'Bonne', 'Été');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (9, 'Humifère', 'Sol riche en matière organique. Croissance vigoureuse.', 'Hortensia', 'Excellente', 'Printemps');

INSERT INTO RECOMMANDATION_PLANTE (ID_PLANTE, TYPE_SOL, RECOMMANDATION, NOM_PLANTE, COMPATIBILITE, SAISON)
VALUES (10, 'Humifère', 'Sol forestier idéal. Préfère l''ombre partielle.', 'Fougère', 'Excellente', 'Automne');

COMMIT;

-- Afficher les résultats
SELECT 'MAINTENANCE' AS TABLE_NAME, COUNT(*) AS NB_ROWS FROM MAINTENANCE
UNION ALL
SELECT 'RECOMMANDATION_PLANTE', COUNT(*) FROM RECOMMANDATION_PLANTE;

DBMS_OUTPUT.PUT_LINE('Tables MAINTENANCE et RECOMMANDATION_PLANTE créées avec succès !');
