-- ============================================================
-- SCRIPT DE CRÉATION DES TABLES POUR SMART CITY
-- ============================================================

-- Table des utilisateurs
CREATE TABLE USERS (
    USERNAME VARCHAR2(50) PRIMARY KEY,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER',
    CREATED_AT DATE DEFAULT SYSDATE
);

-- Table des maisons
CREATE TABLE GEST_MAISON (
    ID NUMBER PRIMARY KEY,
    ADRESSE VARCHAR2(255) NOT NULL,
    SECURITE NUMBER CHECK (SECURITE BETWEEN 0 AND 10),
    STATUS VARCHAR2(50),
    TYPE VARCHAR2(50),
    NBRDESPIECES NUMBER
);

-- Table des résidents
CREATE TABLE GEST_RESIDENT (
    ID VARCHAR2(20) PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    DATE_NAISSANCE DATE,
    ADRESSE VARCHAR2(255),
    TELEPHONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    STATUT VARCHAR2(50),
    SITUATION VARCHAR2(50)
);

-- Table des employés
CREATE TABLE GEST_EMPLOYE (
    ID NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    POSTE VARCHAR2(100),
    SALAIRE NUMBER,
    DATE_EMBAUCHE DATE,
    TELEPHONE VARCHAR2(20),
    EMAIL VARCHAR2(100)
);

-- Séquence pour les employés
CREATE SEQUENCE SEQ_EMPLOYE START WITH 1 INCREMENT BY 1;

-- Table des véhicules
CREATE TABLE GEST_VEHICULE (
    ID NUMBER PRIMARY KEY,
    IMMATRICULATION VARCHAR2(20) UNIQUE NOT NULL,
    MARQUE VARCHAR2(50),
    MODELE VARCHAR2(50),
    TYPE VARCHAR2(50),
    ETAT VARCHAR2(50),
    SERVICE VARCHAR2(100),
    DATE_MAINTENANCE DATE
);

-- Séquence pour les véhicules
CREATE SEQUENCE SEQ_VEHICULE START WITH 1 INCREMENT BY 1;

-- Table des alertes
CREATE TABLE GEST_ALERTES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MAISON NUMBER NOT NULL,
    ZONE VARCHAR2(255),
    NIVEAU NUMBER CHECK (NIVEAU BETWEEN 1 AND 5),
    STATUT VARCHAR2(50),
    DATE_ALERTE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ALERTE_MAISON FOREIGN KEY (ID_MAISON) REFERENCES GEST_MAISON(ID) ON DELETE CASCADE
);

-- Table historique
CREATE TABLE GEST_HISTORIQUE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_RESIDENT VARCHAR2(20),
    ACTION VARCHAR2(100) NOT NULL,
    DETAILS VARCHAR2(500),
    DATE_ACTION DATE DEFAULT SYSDATE,
    UTILISATEUR VARCHAR2(50),
    CONSTRAINT FK_HISTORIQUE_RESIDENT FOREIGN KEY (ID_RESIDENT) REFERENCES GEST_RESIDENT(ID) ON DELETE SET NULL
);

-- Index pour améliorer les performances
CREATE INDEX IDX_RESIDENT_ADRESSE ON GEST_RESIDENT(ADRESSE);
CREATE INDEX IDX_ALERTE_MAISON ON GEST_ALERTES(ID_MAISON);
CREATE INDEX IDX_ALERTE_STATUT ON GEST_ALERTES(STATUT);
CREATE INDEX IDX_HISTORIQUE_DATE ON GEST_HISTORIQUE(DATE_ACTION);
CREATE INDEX IDX_HISTORIQUE_RESIDENT ON GEST_HISTORIQUE(ID_RESIDENT);

-- Trigger pour l'historique lors de l'ajout d'un résident
CREATE OR REPLACE TRIGGER TRG_RESIDENT_INSERT
AFTER INSERT ON GEST_RESIDENT
FOR EACH ROW
BEGIN
    INSERT INTO GEST_HISTORIQUE (ID_RESIDENT, ACTION, DETAILS, UTILISATEUR)
    VALUES (:NEW.ID, 'AJOUT', 'Nouveau résident: ' || :NEW.NOM || ' ' || :NEW.PRENOM, USER);
END;
/

-- Trigger pour l'historique lors de la modification d'un résident
CREATE OR REPLACE TRIGGER TRG_RESIDENT_UPDATE
AFTER UPDATE ON GEST_RESIDENT
FOR EACH ROW
BEGIN
    INSERT INTO GEST_HISTORIQUE (ID_RESIDENT, ACTION, DETAILS, UTILISATEUR)
    VALUES (:NEW.ID, 'MODIFICATION', 'Résident modifié: ' || :NEW.NOM || ' ' || :NEW.PRENOM, USER);
END;
/

-- Trigger pour l'historique lors de la suppression d'un résident
CREATE OR REPLACE TRIGGER TRG_RESIDENT_DELETE
BEFORE DELETE ON GEST_RESIDENT
FOR EACH ROW
BEGIN
    INSERT INTO GEST_HISTORIQUE (ID_RESIDENT, ACTION, DETAILS, UTILISATEUR)
    VALUES (:OLD.ID, 'SUPPRESSION', 'Résident supprimé: ' || :OLD.NOM || ' ' || :OLD.PRENOM, USER);
END;
/

-- Trigger pour créer automatiquement une alerte si sécurité < 3
CREATE OR REPLACE TRIGGER TRG_MAISON_SECURITE
AFTER INSERT OR UPDATE OF SECURITE ON GEST_MAISON
FOR EACH ROW
WHEN (NEW.SECURITE < 3)
BEGIN
    -- Vérifier si une alerte n'existe pas déjà pour cette maison
    DECLARE
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM GEST_ALERTES
        WHERE ID_MAISON = :NEW.ID AND STATUT != 'Traitée';
        
        IF v_count = 0 THEN
            INSERT INTO GEST_ALERTES (ID_MAISON, ZONE, NIVEAU, STATUT)
            VALUES (:NEW.ID, :NEW.ADRESSE, :NEW.SECURITE, 'En attente');
        END IF;
    END;
END;
/

COMMIT;

-- Afficher le résultat
SELECT 'Tables créées avec succès!' AS MESSAGE FROM DUAL;
