-- Agrandir la colonne SERVICE dans la table VEHICULE
ALTER TABLE VEHICULE MODIFY SERVICE VARCHAR2(200);

-- Vérifier la modification
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'VEHICULE' 
AND COLUMN_NAME = 'SERVICE';

EXIT;
