SET LINESIZE 200
SET PAGESIZE 100
COLUMN COLUMN_NAME FORMAT A30
COLUMN DATA_TYPE FORMAT A20
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'VEHICULE' 
ORDER BY COLUMN_ID;
EXIT;
