-- Ajouter la colonne RFID_CODE à la table GEST_RESIDENT
ALTER TABLE GEST_RESIDENT ADD (RFID_CODE VARCHAR2(50));

-- Créer un index pour accélérer la recherche par RFID
CREATE INDEX idx_rfid_code ON GEST_RESIDENT(RFID_CODE);

-- Ajouter quelques codes RFID de test
UPDATE GEST_RESIDENT SET RFID_CODE = 'A1B2C3D4' WHERE ID = 1;
UPDATE GEST_RESIDENT SET RFID_CODE = 'E5F6G7H8' WHERE ID = 2;
UPDATE GEST_RESIDENT SET RFID_CODE = 'I9J0K1L2' WHERE ID = 3;

-- Vérifier la structure
DESC GEST_RESIDENT;

-- Afficher les résidents avec leurs codes RFID
SELECT ID, NOM, PRENOM, RFID_CODE FROM GEST_RESIDENT WHERE RFID_CODE IS NOT NULL;

COMMIT;
